theme: jekyll-theme-dinky
title: Data Science Project Blog
logo: hosh.jpg
show_downloads: False
footer-links:
  github: github.com/HoshAi
  linkedin: https//www.linkedin.com/in/ayodeji-imanuel-39b109175/
  twitter: twitter.com/wagmii_
